# Generated by Django 6.0.6 on 2026-06-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_input', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=5)),
                ('ai_diagnosis', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('serious', 'Serious')], default='mild', max_length=10)),
                ('recommended_speciality', models.CharField(blank=True, max_length=100)),
                ('follow_up_questions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='symptoms.symptomcheck')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
