# Generated by Django 6.0.6 on 2026-06-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(choices=[('general', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('orthopedic', 'Orthopedic'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('gynecologist', 'Gynecologist'), ('ent', 'ENT Specialist'), ('ophthalmologist', 'Ophthalmologist'), ('gastroenterologist', 'Gastroenterologist'), ('pulmonologist', 'Pulmonologist'), ('endocrinologist', 'Endocrinologist'), ('urologist', 'Urologist'), ('oncologist', 'Oncologist')], max_length=50)),
                ('hospital', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(default=4.0)),
                ('available', models.BooleanField(default=True)),
                ('consultation_fee', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('symptoms', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
